Repository kubeflow/kfp-tekton-backend, pull requests merged in 2020-06, with the labels that each got.

#4 init Tekton backend commit
  TEKTON_CHANGELOG.md
  backend/Dockerfile
  backend/src/agent/persistence/client/pipeline_client.go
  backend/src/agent/persistence/client/workflow_client.go
  backend/src/agent/persistence/main.go
  backend/src/agent/persistence/persistence_agent.go
  backend/src/agent/persistence/worker/metrics_reporter.go
  backend/src/apiserver/client/BUILD.bazel
  backend/src/apiserver/client/kubernetes_core_fake.go
  backend/src/apiserver/client/tekton.go
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/model/BUILD.bazel
  backend/src/apiserver/model/resource_reference_test.go
  backend/src/apiserver/resource/BUILD.bazel
  backend/src/apiserver/resource/model_converter.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_util.go
  backend/src/apiserver/server/BUILD.bazel
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/report_server.go
  backend/src/apiserver/server/test_util.go
  backend/src/apiserver/storage/BUILD.bazel
  backend/src/apiserver/storage/run_store.go
  backend/src/common/client/api_server/BUILD.bazel
  backend/src/common/client/api_server/pipeline_client.go
  backend/src/common/client/api_server/run_client.go
  backend/src/common/client/api_server/util.go
  backend/src/common/util/BUILD.bazel
  backend/src/common/util/formatter.go
  backend/src/common/util/scheduled_workflow.go
  backend/src/common/util/template_util.go
  backend/src/common/util/template_util_test.go
  backend/src/common/util/workflow.go
  backend/src/crd/controller/scheduledworkflow/util/BUILD.bazel
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
  backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/BUILD.bazel
  backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/types.go
  backend/src/crd/pkg/client/clientset/versioned/typed/scheduledworkflow/v1beta1/BUILD.bazel
  backend/src/crd/pkg/client/clientset/versioned/typed/scheduledworkflow/v1beta1/scheduledworkflow_client.go
  go.mod
  go.sum
Labels: approved, lgtm, size/XXL

#11 Remove flaky Travis tests
  .travis.yml
Labels: approved, lgtm, size/L

#5 init Tekton UI commit
  frontend/server/k8s-helper.ts
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/Utils.tsx
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/RunDetails.tsx
Labels: approved, lgtm, size/XL

#6 initial instructions for setting up the Tekton KFP
  README.md
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-role.yaml
  manifests/kustomize/base/pipeline/pipeline-runner-role.yaml
Labels: approved, lgtm, size/L

#12 Initial metadata support for output parameters
  backend/metadata_writer/src/metadata_writer.py
  backend/src/common/util/workflow.go
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-writer-deployment.yaml
  manifests/kustomize/base/metadata/metadata-writer-role.yaml
Labels: approved, lgtm, size/L

#16 Fix pipelinerun not found error
  frontend/src/lib/StatusUtils.ts
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/RunDetails.tsx
Labels: approved, lgtm, size/S

#14 Add default catalog and new status for condition
  backend/src/common/util/workflow.go
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/tekton/catalog-condition.yaml
  manifests/kustomize/base/tekton/kustomization.yaml
Labels: approved, lgtm, size/S

#15 Update metadata writer with the new design
  backend/metadata_writer/src/metadata_writer.py
Labels: approved, lgtm, size/M

#17 Update Tekton to 0.13.0
  README.md
  TEKTON_CHANGELOG.md
  backend/Dockerfile.persistenceagent
  backend/src/apiserver/storage/job_store_test.go
  backend/src/common/util/scheduled_workflow_test.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/XL

#18 Add support for Tekton Conditions in UI graphs
  frontend/src/components/Banner.tsx
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/StatusUtils.ts
  frontend/src/lib/Utils.tsx
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/Status.tsx
Labels: approved, lgtm, size/L
